FROM python:3.7
LABEL MAINTAINER="Trim21 <Trim21me@gmail.com>"
WORKDIR /

COPY ./requirements /requirements

RUN pip install -r /requirements/prod.txt

COPY scrapy.cfg /scrapy.cfg
COPY bgm_tv_spider /bgm_tv_spider
COPY app /app

ARG DAO_COMMIT_SHA
ENV COMMIT_SHA=$DAO_COMMIT_SHA

CMD python -m scrapy crawl redis_bgm_tv
