FROM python:3.7
LABEL MAINTAINER="Trim21 <Trim21me@gmail.com>"
WORKDIR /
ENV PIPENV_SYSTEM=1

COPY ./requirements/prod.txt /requirements.txt
RUN pip install -r requirements.txt

COPY app /app

ARG DAO_COMMIT_SHA
ENV COMMIT_SHA=$DAO_COMMIT_SHA

COPY bgm_tv_spider /bgm_tv_spider
COPY scrapy.cfg /scrapy.cfg

CMD python -m scrapy crawl redis_bgm_tv
