FROM python:3.7
LABEL MAINTAINER="Trim21 <Trim21me@gmail.com>"
WORKDIR /

COPY ./requirements/prod.txt /requirements.txt
RUN pip install -r requirements.txt

COPY app /app
COPY video_website_spider /video_website_spider

ARG DAO_COMMIT_SHA
ENV COMMIT_SHA=$DAO_COMMIT_SHA

EXPOSE 8000

CMD python -m celery worker -A app.worker -Q celery-www-queue -l info -c 5
