FROM python:3.7
LABEL MAINTAINER="Trim21 <Trim21me@gmail.com>"
ENV PYTHONPATH=/
WORKDIR /

COPY ./requirements/prod.txt /requirements.txt
RUN pip install -q -r requirements.txt

COPY / /

ARG DAO_COMMIT_SHA
ENV COMMIT_SHA=$DAO_COMMIT_SHA
ARG DAO_COMMIT_TAG
ENV COMMIT_TAG=$DAO_COMMIT_TAG

CMD python -m celery worker -A app.worker -Q celery-www-queue -l info -c 5
