jobs:
  - job: 'Docker'
    pool:
      vmImage: $(vm_image)

    steps:
      - script: |
          SHA=$(Build.SourceVersion)
          SHA=${SHA:0:7}
          REF=$(Build.SourceBranch)

          BRANCH_OR_TAG=$(echo "$REF" | cut -d "/" -f 3- )
          TYPE=$(echo "$REF" | cut -d "/" -f 2 )

          case "$TYPE" in

            tags)
              REF=${BRANCH_OR_TAG}
              SLUG=latest
              ;;

            heads)
              REF=${BRANCH_OR_TAG////.}
              SLUG="${REF}-${SHA}"
              ;;

            *)
              REF=${BRANCH_OR_TAG}
              SLUG="${REF}-${SHA}"
              ;;
          esac

          echo "##vso[task.setvariable variable=SHA]$SHA"
          echo "##vso[task.setvariable variable=REF]$REF"
          echo "##vso[task.setvariable variable=BRANCH_OR_TAG]$BRANCH_OR_TAG"
          echo "##vso[task.setvariable variable=SLUG]$SLUG"

      - script: |
          docker build \
            -t trim21/pol:current \
            --build-arg "COMMIT_SHA=$SHA" \
            --build-arg "COMMIT_REF=$BRANCH_OR_TAG" \
            .
        displayName: Build Docker

      - script: |
          docker login --username trim21 --password $DOCKER_PASS

          Tags=(
            "$REF"
            "$SLUG"
            "$SHA"
          )

          for tag in "${Tags[@]}"; do
            docker tag trim21/pol:current trim21/pol:$tag
            docker push trim21/pol:$tag
          done

        displayName: Publish Docker
        condition: |
          or(
            startsWith(variables['build.sourceBranch'], 'refs/tags/v'),
            startsWith(variables['build.sourceBranch'], 'refs/heads/')
          )
#            in(variables['Build.SourceBranch'],'refs/heads/dev','refs/heads/master')
        env:
          DOCKER_PASS: $(DOCKER_PASS)
