jobs:
  - job: 'Docker'
    pool:
      vmImage: $(vm_image)

    steps:
      - script: |
          SHA=$(Build.SourceVersion)
          SHA=${SHA:0:7}
          REF=$(Build.SourceBranch)

          if [[ ${REF} == refs/tags* ]]; then
            REF=${REF:10}
            SLUG=latest
          else
            REF=${REF:11}
            REF=${REF////.}
            SLUG="${REF:11}-${SHA}"
          fi

          echo "##vso[task.setvariable variable=SHA]$SHA"
          echo "##vso[task.setvariable variable=REF]$REF"
          echo "##vso[task.setvariable variable=SLUG]$SLUG"

      - script: |
          docker build \
            -t current \
            --build-arg "COMMIT_SHA=$SHA" \
            --build-arg "COMMIT_REF=$REF" \
            .
        displayName: Build Docker

      - script: |
          docker login --username trim21 --password $DOCKER_PASS
          Tags=(
            "$REF"
            "$SLUG"
            "$SHA"
          )

          for tag in "${Tags[@]}" ;do
            docker tag current trim21/pol:$tag
            docker push trim21/pol:$tag
          done

        displayName: Publish Docker
        condition: |
          or(
            startsWith(variables['build.sourceBranch'], 'refs/tags/v'),
            startsWith(variables['build.sourceBranch'], 'refs/heads/'),
          )
#            in(variables['Build.SourceBranch'],'refs/heads/dev','refs/heads/master')
        env:
          DOCKER_PASS: $(DOCKER_PASS)
