jobs:
  - job: 'Docker'
    pool:
      vmImage: $(vm_image)

    steps:
      - script: |
          SHA=$(Build.SourceVersion)
          SHA=${SHA:0:7}
          REF=$(Build.SourceBranch)

          BRANCH_OR_TAG=$(echo "$REF" | cut -d "/" -f 3- )
          TYPE=$(echo "$REF" | cut -d "/" -f 2 )

          case "$TYPE" in

            tags)
              REF=${BRANCH_OR_TAG}
              SLUG=latest
              ;;

            heads)
              REF=${BRANCH_OR_TAG////.}
              SLUG="${REF}-${SHA}"
              ;;

            *)
              REF=${BRANCH_OR_TAG}
              SLUG="${REF}-${SHA}"
              ;;
          esac

          echo "##vso[task.setvariable variable=SHA]$SHA"
          echo "##vso[task.setvariable variable=REF]$REF"
          echo "##vso[task.setvariable variable=BRANCH_OR_TAG]$BRANCH_OR_TAG"
          echo "##vso[task.setvariable variable=SLUG]$SLUG"

      - script: |
          docker build \
            -t trim21/pol:current \
            --build-arg "COMMIT_SHA=$SHA" \
            --build-arg "COMMIT_REF=$BRANCH_OR_TAG" \
            .
        displayName: Build Docker

      - script: |
          mkdir -p $(Pipeline.Workspace)/docker
          docker save trim21/pol:current | gzip > $(Pipeline.Workspace)/docker/pol-image.tar.gz
          echo SHA=$SHA >> $(Pipeline.Workspace)/docker/env
          echo SLUG=$SLUG >> $(Pipeline.Workspace)/docker/env
          echo REF=$REF >> $(Pipeline.Workspace)/docker/env
        displayName: Save Docker Image as Artifact

      - publish: $(Pipeline.Workspace)/docker
        artifact: docker
