jobs:
- job: 'Docker'
  pool:
    vmImage: $(vm_image)

  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      buildContext: '$(Build.Repository.LocalPath)'
      command: build
