jobs:
  - job: 'Docker'
    condition: |
      or(
        startsWith(variables['build.sourceBranch'], 'refs/tags/v'),
        startsWith(variables['build.sourceBranch'], 'refs/heads/')
      )
    #            in(variables['Build.SourceBranch'],'refs/heads/dev','refs/heads/master')

    pool:
      vmImage: $(vm_image)

    steps:
      - script: docker login --username trim21 --password $DOCKER_PASS
        displayName: Docker Login
        env:
          DOCKER_PASS: $(DOCKER_PASS)

      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: docker
          path: $(Pipeline.Workspace)/docker

      - script: |
          cat $(Pipeline.Workspace)/docker/pol-image.tar.gz | docker import - trim21/pol:current
          docker images
#          docker load -i $(Pipeline.Workspace)/docker/pol-image
        displayName: Load Docker Image

      - script: |
          docker images
          Tags=(
            "$REF"
            "$SLUG"
            "$SHA"
          )

          for tag in "${Tags[@]}"; do
            docker tag trim21/pol:current trim21/pol:$tag
            docker push trim21/pol:$tag
          done
        displayName: Publish Docker
