jobs:
  - job: 'Docs'
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')
    pool:
      vmImage: $(vm_image)

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 13.x

      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: docs
          path: $(System.DefaultWorkingDirectory)/docs/build/html

      - script: |
          npm install -g --silent gh-pages@2.x.x
          git config user.email "bot@trim21.me"
          git config user.name "Trim21[bot]"
          gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/build/html \
              --repo https://$GITHUB_TOKEN@github.com/Trim21/pol.git
        displayName: Deploy docs to gh-pages branch
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN)
