jobs:
  - job: 'Docs'
    pool:
      vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 13.x

      - task: DownloadPipelineArtifact@2
        inputs:
          source: current
          artifact: docs
          path: '$(Pipeline.Workspace)/docs/build/html'

      - script: touch docs/build/html/.nojekyll
        displayName: Disable jekyll builds

      - script: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email "github@trim21.me"
          git config user.name "azure pipeline"
        displayName: Install and configure dependencies

      - script: |
          gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/build/html \
              --repo https://$GITHUB_TOKEN@github.com/Trim21/pol.git
        displayName: Deploy docs to gh-pages branch
