jobs:
  - job: 'App'
    pool:
      vmImage: $(vm_image)

    steps:
      - task: DockerCompose@0
        displayName: Setup Containers
        inputs:
          action: Run services
          dockerComposeFile: '$(Build.Repository.LocalPath)/.ci/composes/docker-compose.yaml'

      - template: /.ci/templates/steps/install-project.yaml

      - script: pytest --junitxml=junit/test_report.xml --cov=. --cov-report=xml
        displayName: Unittest
        env:
          TESTING: 'true'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: 'junit/test_*.xml'
          testRunTitle: 'Publish test results for Python $(python.version)'

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          failIfCoverageEmpty: true # Optional
