jobs:
  - job: 'App'
    pool:
      vmImage: $(vm_image)

    steps:
      - task: DockerCompose@0
        displayName: Setup Containers
        inputs:
          action: Run services
          dockerComposeFile: '$(Build.Repository.LocalPath)/.ci/composes/docker-compose.yaml'

      - template: /.ci/templates/steps/install-project.yaml

      - script: alembic upgrade head
        displayName: Migrate Tables

      - bash: |
          set -ex
          sudo apt-get install mysql-client -y
          mkdir -p ./tests_data
          curl -sSL https://github.com/Trim21/pol/releases/download/test_data/c.sql.gz -o ./tests_data/all.sql.gz
          gunzip ./tests_data/all.sql.gz

          MYSQL_CLIENT_ARGS="--host=127.0.0.1 --port=3307 --database=$MYSQL_DB -u root -p$MYSQL_PASSWORD"
          mysql $MYSQL_CLIENT_ARGS -e "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'NO_AUTO_CREATE_USER',''));"
          mysql $MYSQL_CLIENT_ARGS < ./tests_data/all.sql
        displayName: Download Test Data

      - script: coverage run -m pytest --junitxml=junit/test_report.xml
        displayName: Unittest
        env:
          TESTING: 'true'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: 'junit/test_*.xml'
          testRunTitle: 'Publish test results for Python $(python.version)'

      - template: /.ci/templates/steps/codecov.yaml
