"""remove bgm_timeline

Revision ID: 0024bccd85ae
Revises: 17c933a401e2
Create Date: 2020-01-12 04:58:55.349333

"""

# revision identifiers, used by Alembic.
revision = '0024bccd85ae'
down_revision = '17c933a401e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
