"""remove map

Revision ID: 0195b3979370
Revises: 0024bccd85ae
Create Date: 2020-01-12 08:56:47.381844

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0195b3979370'
down_revision = '0024bccd85ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjectjson')
    op.create_index(
        op.f('ix_bangumi_bilibili_media_id'),
        'bangumi_bilibili', ['media_id'],
        unique=False
    )
    op.drop_index('bilibilibangumi_media_id', table_name='bangumi_bilibili')
    op.create_index(
        op.f('ix_bangumi_iqiyi_bangumi_id'),
        'bangumi_iqiyi', ['bangumi_id'],
        unique=False
    )
    op.drop_index('iqiyibangumi_bangumi_id', table_name='bangumi_iqiyi')
    op.create_index(op.f('ix_ep_subject_id'), 'ep', ['subject_id'], unique=False)
    op.drop_index('ep_subject_id', table_name='ep')
    op.create_index(
        op.f('ix_ep_source_subject_id'), 'ep_source', ['subject_id'], unique=False
    )
    op.drop_index('epsource_subject_id', table_name='ep_source')
    op.create_index(op.f('ix_relation_map'), 'relation', ['map'], unique=False)
    op.drop_index('relation_map', table_name='relation')
    op.create_index(op.f('ix_subject_map'), 'subject', ['map'], unique=False)
    op.drop_index('subject_map', table_name='subject')
    op.create_index(op.f('ix_tag_text'), 'tag', ['text'], unique=False)
    op.drop_index('tag_text', table_name='tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tag_text', 'tag', ['text'], unique=False)
    op.drop_index(op.f('ix_tag_text'), table_name='tag')
    op.create_index('subject_map', 'subject', ['map'], unique=False)
    op.drop_index(op.f('ix_subject_map'), table_name='subject')
    op.create_index('relation_map', 'relation', ['map'], unique=False)
    op.drop_index(op.f('ix_relation_map'), table_name='relation')
    op.create_index('epsource_subject_id', 'ep_source', ['subject_id'], unique=False)
    op.drop_index(op.f('ix_ep_source_subject_id'), table_name='ep_source')
    op.create_index('ep_subject_id', 'ep', ['subject_id'], unique=False)
    op.drop_index(op.f('ix_ep_subject_id'), table_name='ep')
    op.create_index(
        'iqiyibangumi_bangumi_id', 'bangumi_iqiyi', ['bangumi_id'], unique=False
    )
    op.drop_index(op.f('ix_bangumi_iqiyi_bangumi_id'), table_name='bangumi_iqiyi')
    op.create_index(
        'bilibilibangumi_media_id', 'bangumi_bilibili', ['media_id'], unique=False
    )
    op.drop_index(op.f('ix_bangumi_bilibili_media_id'), table_name='bangumi_bilibili')
    op.create_table(
        'subjectjson',
        sa.Column(
            'id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column('info', mysql.LONGTEXT(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
