"""init

Revision ID: 07e35f39f114
Revises:
Create Date: 2020-01-12 09:18:01.583040

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07e35f39f114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bangumi_bilibili',
        sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('media_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('season_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(
        op.f('ix_bangumi_bilibili_media_id'),
        'bangumi_bilibili', ['media_id'],
        unique=False
    )
    op.create_table(
        'bangumi_iqiyi',
        sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('bangumi_id', sa.String(length=255), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(
        op.f('ix_bangumi_iqiyi_bangumi_id'),
        'bangumi_iqiyi', ['bangumi_id'],
        unique=False
    )
    op.create_table(
        'bangumi_source', sa.Column('source', sa.CHAR(length=255), nullable=False),
        sa.Column('bangumi_id', sa.String(length=255), nullable=False),
        sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.PrimaryKeyConstraint('source', 'bangumi_id')
    )
    op.create_table(
        'bgm_timeline', sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
        sa.Column('user_name', sa.String(length=255), nullable=False),
        sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('time', mysql.INTEGER(display_width=11), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_bgm_timeline_time'), 'bgm_timeline', ['time'], unique=False
    )
    op.create_index(
        op.f('ix_bgm_timeline_user_id'), 'bgm_timeline', ['user_id'], unique=False
    )
    op.create_index(
        op.f('ix_bgm_timeline_user_name'), 'bgm_timeline', ['user_name'], unique=False
    )
    op.create_table(
        'ep', sa.Column('ep_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('name', sa.String(length=400), nullable=False),
        sa.Column('episode', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('ep_id')
    )
    op.create_index(op.f('ix_ep_subject_id'), 'ep', ['subject_id'], unique=False)
    op.create_table(
        'ep_bilibili',
        sa.Column('source_ep_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('ep_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('source_ep_id')
    )
    op.create_table(
        'ep_iqiyi', sa.Column('source_ep_id', sa.String(length=255), nullable=False),
        sa.Column('ep_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('source_ep_id')
    )
    op.create_table(
        'ep_source',
        sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('source', sa.CHAR(length=40), nullable=False),
        sa.Column('source_ep_id', sa.String(length=255), nullable=False),
        sa.Column('bgm_ep_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('episode', mysql.INTEGER(display_width=11), nullable=False),
        sa.PrimaryKeyConstraint('source', 'source_ep_id')
    )
    op.create_index(
        op.f('ix_ep_source_subject_id'), 'ep_source', ['subject_id'], unique=False
    )
    op.create_table(
        'map', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'missing_bangumi', sa.Column('source', sa.CHAR(length=255), nullable=False),
        sa.Column('bangumi_id', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('source', 'bangumi_id')
    )
    op.create_table(
        'relation', sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('relation', sa.String(length=255), nullable=False),
        sa.Column('source', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('target', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column(
            'map',
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            nullable=False
        ),
        sa.Column(
            'removed',
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            nullable=False
        ), sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_map'), 'relation', ['map'], unique=False)
    op.create_table(
        'subject', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('image', sa.String(length=255), nullable=False),
        sa.Column('subject_type', sa.String(length=255), nullable=False),
        sa.Column('name_cn', sa.String(length=255), nullable=False),
        sa.Column('tags', sa.Text(), nullable=False),
        sa.Column('info', sa.Text(), nullable=False),
        sa.Column('score_details', sa.Text(), nullable=False),
        sa.Column('score', sa.String(length=255), nullable=False),
        sa.Column(
            'wishes',
            mysql.INTEGER(display_width=255),
            server_default=sa.text("'0'"),
            nullable=False
        ),
        sa.Column(
            'done',
            mysql.INTEGER(display_width=255),
            server_default=sa.text("'0'"),
            nullable=False
        ),
        sa.Column(
            'doings',
            mysql.INTEGER(display_width=255),
            server_default=sa.text("'0'"),
            nullable=False
        ),
        sa.Column(
            'on_hold',
            mysql.INTEGER(display_width=255),
            server_default=sa.text("'0'"),
            nullable=False
        ),
        sa.Column(
            'dropped',
            mysql.INTEGER(display_width=255),
            server_default=sa.text("'0'"),
            nullable=False
        ),
        sa.Column(
            'map',
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            nullable=False
        ), sa.Column('locked', mysql.TINYINT(display_width=1), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_map'), 'subject', ['map'], unique=False)
    op.create_table(
        'subjectjson', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('info', mysql.LONGTEXT(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'tag', sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('text', sa.CHAR(length=32), nullable=False),
        sa.Column('count', mysql.INTEGER(display_width=11), nullable=False),
        sa.PrimaryKeyConstraint('subject_id', 'text')
    )
    op.create_index(op.f('ix_tag_text'), 'tag', ['text'], unique=False)
    op.create_table(
        'user_submit_bangumi', sa.Column('source', sa.CHAR(length=40), nullable=False),
        sa.Column('subject_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('bangumi_id', sa.String(length=255), nullable=False),
        sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('modify_time', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('source', 'bangumi_id', 'user_id')
    )
    op.create_table(
        'usertoken',
        sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('scope', sa.String(length=255), nullable=False),
        sa.Column('token_type', sa.String(length=255), nullable=False),
        sa.Column('expires_in', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('auth_time', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('access_token', sa.CHAR(length=50), nullable=False),
        sa.Column('refresh_token', sa.CHAR(length=50), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('nickname', sa.String(length=255), nullable=False),
        sa.Column('usergroup', mysql.INTEGER(display_width=11), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertoken')
    op.drop_table('user_submit_bangumi')
    op.drop_index(op.f('ix_tag_text'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('subjectjson')
    op.drop_index(op.f('ix_subject_map'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_relation_map'), table_name='relation')
    op.drop_table('relation')
    op.drop_table('missing_bangumi')
    op.drop_table('map')
    op.drop_index(op.f('ix_ep_source_subject_id'), table_name='ep_source')
    op.drop_table('ep_source')
    op.drop_table('ep_iqiyi')
    op.drop_table('ep_bilibili')
    op.drop_index(op.f('ix_ep_subject_id'), table_name='ep')
    op.drop_table('ep')
    op.drop_index(op.f('ix_bgm_timeline_user_name'), table_name='bgm_timeline')
    op.drop_index(op.f('ix_bgm_timeline_user_id'), table_name='bgm_timeline')
    op.drop_index(op.f('ix_bgm_timeline_time'), table_name='bgm_timeline')
    op.drop_table('bgm_timeline')
    op.drop_table('bangumi_source')
    op.drop_index(op.f('ix_bangumi_iqiyi_bangumi_id'), table_name='bangumi_iqiyi')
    op.drop_table('bangumi_iqiyi')
    op.drop_index(op.f('ix_bangumi_bilibili_media_id'), table_name='bangumi_bilibili')
    op.drop_table('bangumi_bilibili')
    # ### end Alembic commands ###
