name: sentry

on:
  push:
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Sentry cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Get the version
        id: get_version
        run: echo "::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)"

      - name: Run Sentry Cli
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}

          sentry-cli releases new -p pol $VERSION
          sentry-cli releases set-commits --auto $VERSION
          sentry-cli releases finalize "$VERSION"

        env:
          SENTRY_ORG: trim21
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
